Repository anitab-org/anitab-forms-backend, pull requests merged in 2021-02, with the labels that each got.

#52 docs: Modified the setup instructions
  README.md
Labels: Status: Needs Review

#57 feature: Add test structure and some test for token_auth register serializer.
  README.md
  osp/tests.py
  tests/__init__.py
  tests/test_serializer_register.py
  token_auth/tests.py
Labels: Status: Needs Review

#67 docs: Add a documentation section in Readme
  README.md
Labels: Status: Needs Review

#55 feature: Add Docker build
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  main/settings.py
Labels: Status: Needs Review

#59 docs: Added link of contributing guidelines to README
  README.md
Labels: Status: Changes Requested

#66 Added GitHub Actions workflow to run tests
  .github/workflows/tests.yml
  README.md
  docs/github_actions.md
Labels: Status: Needs Review

#83 Document env variables needed to run the backend
  README.md
Labels: Status: Ready to Merge

#92 typo: Fixed link in the README.md
  README.md
Labels: Status: Ready to Merge

#87 docs: Add badges to README
  README.md
Labels: Status: Ready to Merge

#96 docs: Added Windows Setup
  README.md
Labels: Status: Needs Review

#93 Made SendGrid email feature optional for development.
  README.md
  main/settings.py
Labels: Status: Ready to Merge

#98 Improved function naming and created docstrings and type hints for zulip_api.py
  osp/utils/zulip_api.py
  osp/views/zulip_stat.py
Labels: Status: Needs Review

#100 Deleted .github/ISSUE_TEMPLATE folder
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Status: Ready to Merge
