Repository anitab-org/anitab-forms-backend, pull requests merged in 2021-03, with the labels that each got.

#107 docs: updated pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Ready to Merge

#95 feat: Added SECRET_KEY as an environment export.
  .github/workflows/tests.yml
  README.md
  main/settings.py
Labels: Status: Changes Requested

#113 fix: added correct link to code of conduct
  CODE_OF_CONDUCT.md
Labels: Status: Ready to Merge

#99 docs: Move wiki to docusaurus for osp-backend
  README.md
  osp-backend-docusaurus/.gitignore
  osp-backend-docusaurus/README.md
  osp-backend-docusaurus/babel.config.js
  osp-backend-docusaurus/docs/2020-Bismita-Guha.md
  osp-backend-docusaurus/docs/About-AnitaB.org-Open-Source.md
  osp-backend-docusaurus/docs/Automation-and-Filtering.md
  osp-backend-docusaurus/docs/Code-Organization.md
  osp-backend-docusaurus/docs/Coding-Standards.md
  osp-backend-docusaurus/docs/Commit-Message-Style-Guide.md
  osp-backend-docusaurus/docs/Database-Design.md
  osp-backend-docusaurus/docs/Export-Environment-Variables.md
  osp-backend-docusaurus/docs/Fork,-Clone,-Remote-and-Pull-Request.md
  osp-backend-docusaurus/docs/Forms.md
  osp-backend-docusaurus/docs/Future-Ideas.md
  osp-backend-docusaurus/docs/GSoC-All-Final-Reports.md
  osp-backend-docusaurus/docs/Getting-Started.md
  osp-backend-docusaurus/docs/Home.md
  osp-backend-docusaurus/docs/Main-Concepts.md
  osp-backend-docusaurus/docs/Maintainer-Guidelines.md
  osp-backend-docusaurus/docs/Quality-Assurance-Test-Cases.md
  osp-backend-docusaurus/docs/Tech-Stack.md
  osp-backend-docusaurus/docs/Technical-Decisions.md
  osp-backend-docusaurus/docs/User-Authentication.md
  osp-backend-docusaurus/docusaurus.config.js
  osp-backend-docusaurus/package.json
  osp-backend-docusaurus/sidebars.js
  osp-backend-docusaurus/src/css/custom.css
  osp-backend-docusaurus/src/pages/index.js
  osp-backend-docusaurus/src/pages/styles.module.css
  osp-backend-docusaurus/static/.nojekyll
  osp-backend-docusaurus/static/img/favicon.ico
  osp-backend-docusaurus/static/img/logo.png
  osp-backend-docusaurus/yarn.lock
Labels: Status: Ready to Merge

#106 Create config.yml
  .github/workflows/config.yml
Labels: Status: Ready to Merge

#102 fix: Solve error for running tests without Zulip API Key
  .github/workflows/tests.yml
  osp/utils/zulip_api.py
Labels: Status: Needs Review

#117 Added codecov badge to readme.
  README.md
Labels: Status: Ready to Merge

#115 docs : Updated general guidelines
  .github/CONTRIBUTING.md
Labels: Status: Ready to Merge

#110 Add license section
  README.md
Labels: Status: Ready to Merge
